application: hikewithben
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: main_api.api_application

inbound_services:
- warmup

automatic_scaling:
  min_idle_instances: 3
  max_idle_instances: 995

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
